
package Enumeraciones;


public enum Apellidos {
    
    OSTROVSKY, DASCAL, LILLO, LEW, GUTIERREZ, VIEGAS, SICRE, ALVAREZ, ANDRADE, BENITEZ, CASTILLO, CASTRO, CONTRERAS, LOPEZ, GONZALEZ, PEREZ, RODRIGUEZ, SANCHEZ, DIAZ, HERNANDEZ, GARCIA, MARTINEZ, HUANG,WANG, LI, ZHANG, CHEN, LIU, DEVI, YANG, FRANCIA, VARGAS, SILVA, ABOUD, FABRIS;
    
   
    
}
