
package Enumeraciones;


public enum Nombres {
    
    SHARON, AYLEN, PATRICIA, ALEJANDRA, CANDELA, FLORENCIA, JOHANNA, YAMILA, CAROLINA, LUCIA, SOFIA, MARTINA, MARIA, JULIA, PAULA, VALERIA, EMMA, FEDERICO, NAHUEL, ERIC, MATIAS, URIEL, GASTON, ERNESTO, ISAAC, CLAUDIO, IGNACIO, HUGO, MATEO, MARTIN, LUCAS, LEO, DANIEL, ALEJANDRO, MANUEL;
    
    
    
}
